name: Maven Build

# Run workflow for any push to a branch
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  workflow_dispatch:

jobs:
  maven-build:
    uses: telicent-oss/shared-workflows/.github/workflows/maven.yml@main
    permissions:
      contents: write
      id-token: write
      issues: write
      packages: write
      pull-requests: write
    with:
      # No Docker based tests in this repository currently
      USES_DOCKERHUB_IMAGES: false
      # Want to publish SNAPSHOTs from main
      PUBLISH_SNAPSHOTS: true
      MAIN_BRANCH: main
      JAVA_VERSION: 17
      # If running in debug mode, use appropriate logging
      MAVEN_DEBUG_ARGS: -Dlogback.configurationFile=logback-debug.xml
    secrets: inherit
